# Generated by Django 3.2.21 on 2023-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionToken', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('walletAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
